import * as Yup from "yup";

import { ROLE_PATHS } from "@Enums";
import { ADD_EMPLOYEE_VALIDATION_MESSAGES } from "@Forms/employee/addEmployee/addEmployee.validation.messages";
import {
  ADD_EMPLOYEE_NAME_MAX_LENGTH,
  ADD_EMPLOYEE_NAME_MIN_LENGTH,
  ADD_EMPLOYEE_PHONE_PATTERN,
  ADD_EMPLOYEE_USERNAME_MAX_LENGTH,
  ADD_EMPLOYEE_USERNAME_MIN_LENGTH,
  ADD_EMPLOYEE_USERNAME_PATTERN,
} from "@Forms/employee/addEmployee/addEmployee.validation.constants";

const EMPLOYEE_ROLES = [ROLE_PATHS.EMPLOYEE, ROLE_PATHS.WAREHOUSE_MANAGER];

export const addEmployeeValidationSchema = Yup.object({
  firstName: Yup.string()
    .trim()
    .min(ADD_EMPLOYEE_NAME_MIN_LENGTH, ADD_EMPLOYEE_VALIDATION_MESSAGES.FIRST_NAME_MIN)
    .max(ADD_EMPLOYEE_NAME_MAX_LENGTH, ADD_EMPLOYEE_VALIDATION_MESSAGES.FIRST_NAME_MAX)
    .required(ADD_EMPLOYEE_VALIDATION_MESSAGES.FIRST_NAME_REQUIRED),
  lastName: Yup.string()
    .trim()
    .min(ADD_EMPLOYEE_NAME_MIN_LENGTH, ADD_EMPLOYEE_VALIDATION_MESSAGES.LAST_NAME_MIN)
    .max(ADD_EMPLOYEE_NAME_MAX_LENGTH, ADD_EMPLOYEE_VALIDATION_MESSAGES.LAST_NAME_MAX)
    .required(ADD_EMPLOYEE_VALIDATION_MESSAGES.LAST_NAME_REQUIRED),
  email: Yup.string()
    .trim()
    .email(ADD_EMPLOYEE_VALIDATION_MESSAGES.EMAIL_INVALID)
    .required(ADD_EMPLOYEE_VALIDATION_MESSAGES.EMAIL_REQUIRED),
  phone: Yup.string()
    .trim()
    .matches(ADD_EMPLOYEE_PHONE_PATTERN, ADD_EMPLOYEE_VALIDATION_MESSAGES.PHONE_INVALID)
    .required(ADD_EMPLOYEE_VALIDATION_MESSAGES.PHONE_REQUIRED),
  username: Yup.string()
    .trim()
    .min(
      ADD_EMPLOYEE_USERNAME_MIN_LENGTH,
      ADD_EMPLOYEE_VALIDATION_MESSAGES.USERNAME_MIN,
    )
    .max(
      ADD_EMPLOYEE_USERNAME_MAX_LENGTH,
      ADD_EMPLOYEE_VALIDATION_MESSAGES.USERNAME_MAX,
    )
    .matches(
      ADD_EMPLOYEE_USERNAME_PATTERN,
      ADD_EMPLOYEE_VALIDATION_MESSAGES.USERNAME_INVALID,
    )
    .required(ADD_EMPLOYEE_VALIDATION_MESSAGES.USERNAME_REQUIRED),
  role: Yup.string()
    .oneOf(EMPLOYEE_ROLES, ADD_EMPLOYEE_VALIDATION_MESSAGES.ROLE_INVALID)
    .required(ADD_EMPLOYEE_VALIDATION_MESSAGES.ROLE_REQUIRED),
});
