import {
  COMPANY_TYPE_OPTIONS,
  CONTACT_POSITION_OPTIONS,
  INDIAN_STATE_AND_UNION_TERRITORY_OPTIONS,
} from "@Enums";

export const COMPANY_DETAILS_TYPE_OPTIONS = COMPANY_TYPE_OPTIONS;
export const COMPANY_DETAILS_CONTACT_POSITION_OPTIONS =
  CONTACT_POSITION_OPTIONS;
export const COMPANY_DETAILS_STATE_OPTIONS =
  INDIAN_STATE_AND_UNION_TERRITORY_OPTIONS;
