import { COMPANY_TYPE_OPTIONS, CONTACT_POSITION_OPTIONS } from "@Enums";

export const COMPANY_DETAILS_TYPE_OPTIONS = COMPANY_TYPE_OPTIONS;
export const COMPANY_DETAILS_CONTACT_POSITION_OPTIONS =
  CONTACT_POSITION_OPTIONS;
