import * as Yup from "yup";

import { ROLE_PATHS } from "@Enums";
import { EMPLOYEE_VALIDATION_MESSAGES } from "@Forms/employee/employee.validation.messages";
import {
  EMPLOYEE_NAME_MAX_LENGTH,
  EMPLOYEE_NAME_MIN_LENGTH,
  EMPLOYEE_PHONE_PATTERN,
  EMPLOYEE_USERNAME_MAX_LENGTH,
  EMPLOYEE_USERNAME_MIN_LENGTH,
  EMPLOYEE_USERNAME_PATTERN,
} from "@Forms/employee/employee.validation.constants";

const EMPLOYEE_ROLES = [ROLE_PATHS.EMPLOYEE, ROLE_PATHS.WAREHOUSE_MANAGER];

export const employeeValidationSchema = Yup.object({
  firstName: Yup.string()
    .trim()
    .min(EMPLOYEE_NAME_MIN_LENGTH, EMPLOYEE_VALIDATION_MESSAGES.FIRST_NAME_MIN)
    .max(EMPLOYEE_NAME_MAX_LENGTH, EMPLOYEE_VALIDATION_MESSAGES.FIRST_NAME_MAX)
    .required(EMPLOYEE_VALIDATION_MESSAGES.FIRST_NAME_REQUIRED),
  lastName: Yup.string()
    .trim()
    .min(EMPLOYEE_NAME_MIN_LENGTH, EMPLOYEE_VALIDATION_MESSAGES.LAST_NAME_MIN)
    .max(EMPLOYEE_NAME_MAX_LENGTH, EMPLOYEE_VALIDATION_MESSAGES.LAST_NAME_MAX)
    .required(EMPLOYEE_VALIDATION_MESSAGES.LAST_NAME_REQUIRED),
  email: Yup.string()
    .trim()
    .email(EMPLOYEE_VALIDATION_MESSAGES.EMAIL_INVALID)
    .required(EMPLOYEE_VALIDATION_MESSAGES.EMAIL_REQUIRED),
  phone: Yup.string()
    .trim()
    .matches(EMPLOYEE_PHONE_PATTERN, EMPLOYEE_VALIDATION_MESSAGES.PHONE_INVALID)
    .required(EMPLOYEE_VALIDATION_MESSAGES.PHONE_REQUIRED),
  username: Yup.string()
    .trim()
    .min(
      EMPLOYEE_USERNAME_MIN_LENGTH,
      EMPLOYEE_VALIDATION_MESSAGES.USERNAME_MIN,
    )
    .max(
      EMPLOYEE_USERNAME_MAX_LENGTH,
      EMPLOYEE_VALIDATION_MESSAGES.USERNAME_MAX,
    )
    .matches(
      EMPLOYEE_USERNAME_PATTERN,
      EMPLOYEE_VALIDATION_MESSAGES.USERNAME_INVALID,
    )
    .required(EMPLOYEE_VALIDATION_MESSAGES.USERNAME_REQUIRED),
  role: Yup.string()
    .oneOf(EMPLOYEE_ROLES, EMPLOYEE_VALIDATION_MESSAGES.ROLE_INVALID)
    .required(EMPLOYEE_VALIDATION_MESSAGES.ROLE_REQUIRED),
});
