/** Temporary backend-shaped stock records used until the list API is ready. */
export const DUMMY_STOCKS = [
  {
    _id: "stock-001",
    product_name: "CG Power 7.5 HP Three Phase Motor",
    sku: "CG-MTR-075",
    brand: "CG Power",
    category: "motor",
    model: "NG80M-4",
    unit: "unit",
    available_quantity: 48,
    reserved_quantity: 8,
    damaged_quantity: 1,
    reorder_level: 18,
    unit_price: 18000,
    warehouse_locations: [
      { _id: "loc-001-a", warehouse_name: "Vadodara Main", rack_number: "M-A12", quantity: 34 },
      { _id: "loc-001-b", warehouse_name: "Ahmedabad Depot", rack_number: "M-C04", quantity: 14 },
    ],
    specifications: { power: "7.5 HP", phase: "Three phase", speed: "1440 RPM", efficiency: "IE3" },
  },
  {
    _id: "stock-002",
    product_name: "Premium Helical Gearbox",
    sku: "PT-GBX-120",
    brand: "Premium Transmission",
    category: "gearbox",
    model: "PBL 120",
    unit: "unit",
    available_quantity: 12,
    reserved_quantity: 4,
    damaged_quantity: 2,
    reorder_level: 15,
    unit_price: 44000,
    warehouse_locations: [
      { _id: "loc-002-a", warehouse_name: "Vadodara Main", rack_number: "G-B08", quantity: 12 },
    ],
    specifications: { ratio: "20:1", torque: "820 Nm", mounting: "Foot mounted", casing: "Cast iron" },
  },
  {
    _id: "stock-003",
    product_name: "KEG 3 HP Three Phase Motor",
    sku: "KEG-MTR-030",
    brand: "Kirloskar Electric",
    category: "motor",
    model: "KEM90S",
    unit: "unit",
    available_quantity: 27,
    reserved_quantity: 5,
    damaged_quantity: 0,
    reorder_level: 12,
    unit_price: 13000,
    warehouse_locations: [
      { _id: "loc-003-a", warehouse_name: "Vadodara Main", rack_number: "M-A06", quantity: 20 },
      { _id: "loc-003-b", warehouse_name: "Surat Depot", rack_number: "M-D02", quantity: 7 },
    ],
    specifications: { power: "3 HP", phase: "Three phase", speed: "2880 RPM", efficiency: "IE2" },
  },
  {
    _id: "stock-004",
    product_name: "CG Openwell Submersible Pump",
    sku: "CG-PMP-OW5",
    brand: "CG Power",
    category: "pump",
    model: "OW5-15",
    unit: "unit",
    available_quantity: 9,
    reserved_quantity: 2,
    damaged_quantity: 1,
    reorder_level: 14,
    unit_price: 24000,
    warehouse_locations: [
      { _id: "loc-004-a", warehouse_name: "Vadodara Main", rack_number: "P-A03", quantity: 9 },
    ],
    specifications: { power: "5 HP", head: "15–52 m", discharge: "420 LPM", outlet: "65 mm" },
  },
  {
    _id: "stock-005",
    product_name: "L&T Automatic Power Factor Panel",
    sku: "LT-APFC-440",
    brand: "L&T",
    category: "electrical",
    model: "APFC-440-50",
    unit: "panel",
    available_quantity: 6,
    reserved_quantity: 1,
    damaged_quantity: 0,
    reorder_level: 5,
    unit_price: 92000,
    warehouse_locations: [
      { _id: "loc-005-a", warehouse_name: "Ahmedabad Depot", rack_number: "E-P01", quantity: 6 },
    ],
    specifications: { voltage: "440 V", capacity: "50 kVAr", stages: "6 stage", enclosure: "IP54" },
  },
  {
    _id: "stock-006",
    product_name: "CG Emotron Variable Frequency Drive",
    sku: "CG-VFD-110",
    brand: "CG Drives",
    category: "drive",
    model: "FDU48-022",
    unit: "unit",
    available_quantity: 18,
    reserved_quantity: 3,
    damaged_quantity: 0,
    reorder_level: 8,
    unit_price: 36500,
    warehouse_locations: [
      { _id: "loc-006-a", warehouse_name: "Vadodara Main", rack_number: "D-C05", quantity: 11 },
      { _id: "loc-006-b", warehouse_name: "Ahmedabad Depot", rack_number: "D-A09", quantity: 7 },
    ],
    specifications: { power: "11 kW", input: "Three phase", protection: "IP20", communication: "Modbus RTU" },
  },
  {
    _id: "stock-007",
    product_name: "Polycab Copper Power Cable 6 sq mm",
    sku: "PC-CBL-006",
    brand: "Polycab",
    category: "cable",
    model: "FRLS-4C-6",
    unit: "metre",
    available_quantity: 860,
    reserved_quantity: 240,
    damaged_quantity: 18,
    reorder_level: 300,
    unit_price: 285,
    warehouse_locations: [
      { _id: "loc-007-a", warehouse_name: "Vadodara Main", rack_number: "C-R02", quantity: 500 },
      { _id: "loc-007-b", warehouse_name: "Surat Depot", rack_number: "C-R01", quantity: 360 },
    ],
    specifications: { cores: "4 core", conductor: "Copper", insulation: "FRLS", voltage_grade: "1.1 kV" },
  },
  {
    _id: "stock-008",
    product_name: "SKF Deep Groove Ball Bearing",
    sku: "SKF-BRG-6205",
    brand: "SKF",
    category: "bearing",
    model: "6205-2Z/C3",
    unit: "piece",
    available_quantity: 0,
    reserved_quantity: 0,
    damaged_quantity: 0,
    reorder_level: 25,
    unit_price: 780,
    warehouse_locations: [],
    specifications: { bore: "25 mm", outside_diameter: "52 mm", width: "15 mm", clearance: "C3" },
  },
  {
    _id: "stock-009",
    product_name: "Premium Worm Gear Motor",
    sku: "PT-WGM-063",
    brand: "Premium Transmission",
    category: "gearbox",
    model: "PWS 063",
    unit: "unit",
    available_quantity: 22,
    reserved_quantity: 6,
    damaged_quantity: 0,
    reorder_level: 10,
    unit_price: 27500,
    warehouse_locations: [
      { _id: "loc-009-a", warehouse_name: "Vadodara Main", rack_number: "G-C12", quantity: 16 },
      { _id: "loc-009-b", warehouse_name: "Surat Depot", rack_number: "G-B03", quantity: 6 },
    ],
    specifications: { ratio: "30:1", motor_power: "1.5 kW", mounting: "Universal", output: "Hollow shaft" },
  },
  {
    _id: "stock-010",
    product_name: "CG Mini Self Priming Pump",
    sku: "CG-PMP-MN2",
    brand: "CG Power",
    category: "pump",
    model: "Mini Samudra II",
    unit: "unit",
    available_quantity: 31,
    reserved_quantity: 7,
    damaged_quantity: 4,
    reorder_level: 12,
    unit_price: 6800,
    warehouse_locations: [
      { _id: "loc-010-a", warehouse_name: "Vadodara Main", rack_number: "P-B07", quantity: 19 },
      { _id: "loc-010-b", warehouse_name: "Ahmedabad Depot", rack_number: "P-A02", quantity: 12 },
    ],
    specifications: { power: "1 HP", head: "6–30 m", discharge: "3200 LPH", suction: "8 m" },
  },
];

export function getDummyStockList({ page = 1, limit = 20, search = "" } = {}) {
  const query = search.trim().toLowerCase();
  const matching = query
    ? DUMMY_STOCKS.filter((stock) =>
        [stock.product_name, stock.sku, stock.brand, stock.category, stock.model]
          .some((value) => value.toLowerCase().includes(query)),
      )
    : DUMMY_STOCKS;
  const start = (page - 1) * limit;

  return {
    stocks: matching.slice(start, start + limit),
    pagination: {
      page,
      limit,
      total: matching.length,
      total_pages: Math.ceil(matching.length / limit),
    },
  };
}

export default DUMMY_STOCKS;
