import {
  COLUMN_TYPES,
  MOBILE_SLOTS,
  PRODUCT_CATEGORY_OPTIONS,
  PRODUCT_STATUS_OPTIONS,
} from "@Enums";
import { Badge } from "@shadcnComponent/badge";
import ProductCategoryBadge from "@screenComponent/products/productCategoryBadge";
import {
  formatCurrency,
  formatNumber,
  formatPercentage,
  formatRange,
} from "@screenComponent/products/product.utils";

const optionalValue = (value) => value || "—";

export const PRODUCT_COLUMNS = [
  {
    key: "productCode",
    header: "Product code",
    filterLabel: "Product code",
    type: COLUMN_TYPES.TEXT,
    field: "productCode",
    sortKey: "product_code",
    filterKey: "product_code",
    className: "whitespace-nowrap font-medium",
    mobile: MOBILE_SLOTS.SECONDARY,
    width: "180px",
  },
  {
    key: "name",
    header: "Product name",
    filterLabel: "Product name",
    type: COLUMN_TYPES.TEXT,
    field: "name",
    sortKey: "name",
    filterKey: "name",
    className: "min-w-56 font-medium",
    mobile: MOBILE_SLOTS.PRIMARY,
    width: "320px",
  },
  {
    key: "purchasePrice",
    header: "Purchase price",
    filterLabel: "Purchase price",
    type: COLUMN_TYPES.NUMBER,
    field: "purchasePrice",
    sortKey: "purchase_price",
    filterKey: "purchase_price",
    className: "whitespace-nowrap tabular-nums",
    mobile: MOBILE_SLOTS.META,
    width: "180px",
    render: (product) => formatCurrency(product.purchasePrice),
  },
  {
    key: "salePrice",
    header: "Sale price",
    filterLabel: "Sale price",
    type: COLUMN_TYPES.NUMBER,
    field: "salePrice",
    sortKey: "sale_price",
    filterKey: "sale_price",
    className: "whitespace-nowrap tabular-nums",
    mobile: MOBILE_SLOTS.META,
    width: "180px",
    render: (product) => formatCurrency(product.salePrice),
  },
  {
    key: "discountAmount",
    header: "Discount amount",
    type: COLUMN_TYPES.CUSTOM,
    field: "discountAmount",
    className: "whitespace-nowrap tabular-nums",
    width: "220px",
    render: (product) => formatRange(product.discountAmount, formatNumber),
  },
  {
    key: "discountPercentage",
    header: "Discount %",
    type: COLUMN_TYPES.CUSTOM,
    field: "discountPercentage",
    className: "whitespace-nowrap tabular-nums",
    width: "180px",
    render: (product) =>
      formatRange(product.discountPercentage, formatPercentage, "-"),
  },
  {
    key: "category",
    header: "Category",
    filterLabel: "Category",
    type: COLUMN_TYPES.SELECT,
    field: "category",
    sortKey: "category",
    filterKey: "category",
    options: PRODUCT_CATEGORY_OPTIONS,
    allOptionLabel: "All categories",
    mobile: MOBILE_SLOTS.BADGE,
    width: "180px",
    render: (product) => <ProductCategoryBadge category={product.category} />,
  },
  {
    key: "agency",
    header: "Agency/Company",
    filterLabel: "Agency/Company",
    type: COLUMN_TYPES.TEXT,
    field: "agency",
    sortKey: "agency",
    filterKey: "agency",
    mobile: MOBILE_SLOTS.META,
    className: "min-w-72 font-medium",
    width: "320px",
    render: (product) => optionalValue(product.agencyName || product.agency),
  },
  {
    key: "gstPercentage",
    header: "GST",
    filterLabel: "GST percentage",
    type: COLUMN_TYPES.NUMBER,
    field: "gstPercentage",
    sortKey: "gst_percentage",
    filterKey: "gst_percentage",
    className: "whitespace-nowrap tabular-nums",
    width: "140px",
    render: (product) => formatPercentage(product.gstPercentage),
  },
  {
    key: "modelNumber",
    header: "Model number",
    filterLabel: "Model number",
    type: COLUMN_TYPES.TEXT,
    field: "modelNumber",
    sortKey: "model_number",
    filterKey: "model_number",
    className: "whitespace-nowrap",
    mobile: MOBILE_SLOTS.META,
    width: "200px",
    render: (product) => optionalValue(product.modelNumber),
  },
  {
    key: "description",
    header: "Description",
    type: COLUMN_TYPES.TEXT,
    field: "description",
    filterKey: "description",
    className: "max-w-sm truncate text-muted-foreground",
    width: "380px",
    render: (product) => optionalValue(product.description),
  },
  {
    key: "createdAt",
    header: "Created",
    filterLabel: "Created",
    type: COLUMN_TYPES.DATE_TIME,
    field: "createdAt",
    sortKey: "created_at",
    filterKey: "created",
    className: "whitespace-nowrap text-muted-foreground",
    mobile: MOBILE_SLOTS.META,
    mobileLabel: "Created",
    width: "210px",
  },
  {
    key: "updatedAt",
    header: "Updated",
    filterLabel: "Updated",
    type: COLUMN_TYPES.DATE_TIME,
    field: "updatedAt",
    sortKey: "updated_at",
    filterKey: "updated",
    className: "whitespace-nowrap text-muted-foreground",
    mobile: MOBILE_SLOTS.META,
    mobileLabel: "Updated",
    width: "210px",
  },
  {
    key: "status",
    header: "Status",
    filterLabel: "Status",
    type: COLUMN_TYPES.SELECT,
    field: "isActive",
    sortKey: "is_active",
    filterKey: "is_active",
    options: PRODUCT_STATUS_OPTIONS,
    allOptionLabel: "All statuses",
    width: "150px",
    mobile: MOBILE_SLOTS.BADGE,
    render: (product) => (
      <Badge variant={product.isActive ? "success" : "destructive"}>
        {product.isActive ? "Active" : "Inactive"}
      </Badge>
    ),
  },
];
