import {
  AGENCY_OPTIONS,
  COLUMN_TYPES,
  MOBILE_SLOTS,
  PRODUCT_CATEGORY_OPTIONS,
} from "@Enums";
import ProductAgencyBadge from "@screenComponent/products/productAgencyBadge";
import ProductCategoryBadge from "@screenComponent/products/productCategoryBadge";

const optionalValue = (value) => value || "—";

export const PRODUCT_COLUMNS = [
  {
    key: "productCode",
    header: "Product code",
    filterLabel: "Product code",
    type: COLUMN_TYPES.TEXT,
    field: "productCode",
    sortKey: "product_code",
    filterKey: "product_code",
    className: "whitespace-nowrap font-medium",
    mobile: MOBILE_SLOTS.SECONDARY,
    width: "180px",
  },
  {
    key: "name",
    header: "Product name",
    filterLabel: "Product name",
    type: COLUMN_TYPES.TEXT,
    field: "name",
    sortKey: "name",
    filterKey: "name",
    className: "min-w-56 font-medium",
    mobile: MOBILE_SLOTS.PRIMARY,
    width: "320px",
  },
  {
    key: "category",
    header: "Category",
    filterLabel: "Category",
    type: COLUMN_TYPES.SELECT,
    field: "category",
    sortKey: "category",
    filterKey: "category",
    options: PRODUCT_CATEGORY_OPTIONS,
    allOptionLabel: "All categories",
    mobile: MOBILE_SLOTS.BADGE,
    width: "180px",
    render: (product) => <ProductCategoryBadge category={product.category} />,
  },
  {
    key: "agency",
    header: "Agency/Company",
    filterLabel: "Agency/Company",
    type: COLUMN_TYPES.SELECT,
    field: "agency",
    sortKey: "agency",
    filterKey: "agency",
    options: AGENCY_OPTIONS,
    allOptionLabel: "All agencies",
    mobile: MOBILE_SLOTS.META,
    width: "180px",
    render: (product) => <ProductAgencyBadge agency={product.agency} />,
  },
  {
    key: "modelNumber",
    header: "Model number",
    filterLabel: "Model number",
    type: COLUMN_TYPES.TEXT,
    field: "modelNumber",
    sortKey: "model_number",
    filterKey: "model_number",
    className: "whitespace-nowrap",
    mobile: MOBILE_SLOTS.META,
    width: "200px",
    render: (product) => optionalValue(product.modelNumber),
  },
  {
    key: "description",
    header: "Description",
    type: COLUMN_TYPES.TEXT,
    field: "description",
    filterKey: "description",
    className: "max-w-sm truncate text-muted-foreground",
    width: "380px",
    render: (product) => optionalValue(product.description),
  },
  {
    key: "createdAt",
    header: "Created",
    filterLabel: "Created",
    type: COLUMN_TYPES.DATE_TIME,
    field: "createdAt",
    sortKey: "created_at",
    filterKey: "created",
    className: "whitespace-nowrap text-muted-foreground",
    mobile: MOBILE_SLOTS.META,
    mobileLabel: "Created",
    width: "210px",
  },
  {
    key: "updatedAt",
    header: "Updated",
    filterLabel: "Updated",
    type: COLUMN_TYPES.DATE_TIME,
    field: "updatedAt",
    sortKey: "updated_at",
    filterKey: "updated",
    className: "whitespace-nowrap text-muted-foreground",
    mobile: MOBILE_SLOTS.META,
    mobileLabel: "Updated",
    width: "210px",
  },
];
