import { COMPANY_TYPES } from "@Enums";

export const SALES_ORDER_CUSTOMER_COMPANY_TYPES = Object.freeze([
  COMPANY_TYPES.CUSTOMER,
  COMPANY_TYPES.BOTH,
]);

export const SALES_ORDER_SUPPLIER_COMPANY_TYPES = Object.freeze([
  COMPANY_TYPES.SUPPLIER,
  COMPANY_TYPES.BOTH,
]);
